version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: terminus
    main: ./cmd/terminus
    binary: terminus-golang
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/deviantintegral/terminus-golang/pkg/version.version={{ .Version }}
      - -X github.com/deviantintegral/terminus-golang/pkg/version.commit={{ .ShortCommit }}

archives:
  - id: terminus
    formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true

release:
  # Use existing release and notes created by release-please
  mode: keep-existing
